### ISSUE TITLE
从3月5日更新用到现在发现海钓的小bug

### ISSUE THREAD

**Issue by zz2592900** [dereklee0310/RussianFishing4Script#10]
饵到设定的时间该关线杯时抽饵时（沉底抽也会有）、有时会关了线杯不抽饵直接把饵收回来了。大概因为什么检测不到延时导致的吧。

**Comment by zz2592900** [comment]
大佬，不知道左键锁定的时长出问题了吗，按最长的设置，上鱼时会卡住。

**Comment by zz2592900** [comment]
大佬，是不是左键锁定的时长出问题了，按最长的设置，上鱼时会卡住。

**Comment by dereklee0310** [comment]
1. 可能是滑口導致的
2. 麻煩具體描述下問題的情境和您海釣的設定
3. 更新到最新一版看看問題是否還會發生

**Comment by dereklee0310** [comment]
請你貼一下config.ini裡海釣的設定
收魚是指提竿收魚嗎? 我不太清楚你所說的卡住是什麼意思
你可以貼下卡住時命令行的輸出，或是透過Wechat傳視頻給我以便定位問題

**Comment by zz2592900** [comment]
> 請你貼一下config.ini裡海釣的設定 收魚是指提竿收魚嗎? 我不太清楚你所說的卡住是什麼意思 你可以貼下卡住時命令行的輸出，或是透過Wechat傳視頻給我以便定位問題

不是提杆，就收鱼，windows的长按锁定键没触发导致卡住。不知道是不是个例

**Comment by zz2592900** [comment]
https://github.com/dereklee0310/RussianFishing4Script/raw/main/static/readme/clicklock.png

**Comment by dereklee0310** [comment]
舊版本也會有問題嗎?

**Comment by zz2592900** [comment]
> 舊版本也會有問題嗎?

刚换新版的时候就出现了

**Comment by dereklee0310** [comment]
修改`player.py`第182行的duration為2.2可以暫時解決問題

**Comment by dereklee0310** [comment]
不抽餌問題的部分請你先嘗試不切換畫面看看是否還會發生，沒有其他資訊我很難判斷原因。

**Comment by zz2592900** [comment]
> 不抽餌問題的部分請你先嘗試不切換畫面看看是否還會發生，沒有其他資訊我很難判斷原因。

还是会遇到。修改过tighten_duration = 1.04，把它改小，不知道有没影响。

**Comment by dereklee0310** [comment]
遊戲是全屏運行的嗎? 可能是誤判背景的上魚標誌導致開始收線

**Comment by zz2592900** [comment]
> 遊戲是全屏運行的嗎? 可能是誤判背景的上魚標誌導致開始收線
窗口运行的。跟丢饵下去没到底就抽的几率差不多，重启就是了。

**Comment by dereklee0310** [comment]
直接收線只有誤判上魚標誌這一種可能，如果切換成無邊框模式後還是無法解決的話，
請將錄製遊戲畫面並透過Mail或Wechat寄送給我。
