### ISSUE TITLE
大佬有没可能考虑更改下海钓的提杆侦测方式。

### ISSUE THREAD

**Issue by zz2592900** [dereklee0310/RussianFishing4Script#11]
鱼上钩后线距000或者005的时候再提杆，不知是否可行。

**Comment by dereklee0310** [comment]
已在計畫中，之後會提供選項讓使用者切換普通線杯/000/005 三種辨識方式

**Comment by zz2592900** [comment]
> 已在計畫中，之後會提供選項讓使用者切換普通線杯/000/005 三種辨識方式

  感觉辨识000，005的功能最好放在一起混合辨识，倒钓的线杯有几率收成000，如果辨识不到005，脚本怕是会卡住。
