### ISSUE TITLE
徵求簡體中文圖片集

### ISSUE THREAD

**Issue by dereklee0310** [dereklee0310/RussianFishing4Script#12]
- 請參考static/en中的圖片，擷取對應的中文版圖片並新增至static/zh-CN資料夾。
- 為統一圖片品質，螢幕解析度2k為佳。
- 如果解析度並非2k，請先測試或描述你的螢幕解析度。
- 提交方式: PR

**Comment by Lance880822** [comment]
請問可以做繁體中文嗎?

**Comment by dereklee0310** [comment]
新增一個zh-TW資料夾並添加繁體版的圖片即可。
後續添加新功能時可能還會需要請你提供相關圖片，你可以考慮下。

**Comment by dereklee0310** [comment]
已有志願者提供
