### ISSUE TITLE
大佬，海图在风浪大或杆子抬太高钓竹刀鱼时候鱼会直接飞上来不需要抬杆。

### ISSUE THREAD

**Issue by zz2592900** [dereklee0310/RussianFishing4Script#13]
但是脚本就直接卡在 收鱼护放生界面了，希望大佬有空优化下。

**Comment by dereklee0310** [comment]
直接進入戶/放生介面的話會在收線逾時(60s)之後重新拋竿，所以不會有完全卡死的問題。
如果發生頻率很高的話我再優化下。

**Comment by zz2592900** [comment]
> 直接進入戶/放生介面的話會在收線逾時(60s)之後重新拋竿，所以不會有完全卡死的問題。 如果發生頻率很高的話我再優化下。

风浪大的时候还频率挺高的,杆子得很低小鱼才飞不上来，脚本会卡在没有抬杆指令的阶段。
如果要等脚本超时挺影响效率，而且我感觉脚本超时后并没有收鱼入护，不知道是不是错觉，都是看太久了都直接收了重启脚本。

**Comment by dereklee0310** [comment]
如果等待約兩分鐘還是沒有入戶的話，請你貼下命令行的輸出。
以下是目前的版本應該會有的輸出，且在Resetting階段會檢測是否收到了魚並入戶/放生:
```
...
INFO: Retrieving
INFO: Resetting
...
```

**Comment by zz2592900** [comment]
> 如果等待約兩分鐘還是沒有入戶的話，請你貼下命令行的輸出。 以下是目前的版本應該會有的輸出，且在Resetting階段會檢測是否收到了魚並入戶/放生:
> 
> ```
> ...
> INFO: Retrieving
> INFO: Resetting
> ...
> ```

我杆抬高点钓竹刀鱼会直接收鱼略过了脚本抬杆的指令，确实会有脚本指令检测鱼的入护放生，就是有点久。

**Comment by dereklee0310** [comment]
已修復
