### ISSUE TITLE
python harvest.py Error

### ISSUE THREAD

**Issue by gg31839** [dereklee0310/RussianFishing4Script#14]
原地掛機自動挖餌+自動補充體力 錯誤

G:\RussianFishing4Script-main\src>python harvest.py
Are you ready to start harvesting baits? [Y/n] Y
The bot has been started
Low energy level
Low energy level
Consume carrot
Low energy level
Low energy level
Harvest baits
Traceback (most recent call last):
  File "G:\RussianFishing4Script-main\src\harvest.py", line 70, in <module>
    harvest_baits(shovel_spoon_shortcut)
TypeError: harvest_baits() takes 0 positional arguments but 1 was given

**Comment by dereklee0310** [comment]
將70行修改為harvest_baits()即可，
已修復但尚未更新至GitHub。
