### ISSUE TITLE
[FEATURE] Keep Unmarked Bait Fish

### ISSUE THREAD

**Issue by tnpe** [dereklee0310/RussianFishing4Script#18]
The current version supports keeping all fishes using "-a" flag or keeping marked fishes only using the "-m" flag. 

In addition to these two options, I am wondering if the feature of keeping some bait fish, e.g., saithe, even if they are unmarked while keeping marked fish only for those cannot be used to make biat could be added in a later version.  Thanks!

**Comment by dereklee0310** [comment]
Seems like a good idea.
It would be better if you could provide a list of fish types that should bypass the mark checking mechanism, e.g. saithe, mackerel, etc. In this case the user can whitelist the fish they want to keep to override the rule.

**Comment by dereklee0310** [comment]
Whitelist for release of unmarked fish has been added, supporting mackerel, saithe, herring, squid, scallop, and mussel.
