### ISSUE TITLE
[BUG]static folder

### ISSUE THREAD

**Issue by asqwedcxz741** [dereklee0310/RussianFishing4Script#19]
There seems to be no image recognition folder uploaded for Simplified Chinese and Traditional Chinese in the static folder
![QQ截图20240407104407](https://github.com/dereklee0310/RussianFishing4Script/assets/46841966/7988c3d8-5e6d-46bc-8a1e-ca66a8ed891a)

**Comment by dereklee0310** [comment]
Fixed.
