### ISSUE TITLE
[BUG]简中的喝茶吃萝卜似乎不能识别，换成繁体可以识别

### ISSUE THREAD

**Issue by zz2592900** [dereklee0310/RussianFishing4Script#20]
如题

**Comment by dereklee0310** [comment]
看起來是因為圖片來源的字體不一樣導致的，你可以暫時先用繁體中文的版本。

**Comment by zz2592900** [comment]
> 看起來是因為圖片來源的字體不一樣導致的，你可以暫時先用繁體中文的版本。

 我试了下从t键截取的图片识别成功了，背包食品里的图片不行。

**Comment by dereklee0310** [comment]
![carrot](https://github.com/dereklee0310/RussianFishing4Script/assets/76050708/f81d6760-15b6-405f-8c09-327ac81ba876)
請你將圖片替換成這個，看看是否能辨識成功，如果可以的話我再把其他圖片一併更新。

**Comment by zz2592900** [comment]
請你將圖片替換成這個，看看是否能辨識成功，如果可以的話我再把其他圖片一併更新。

不行，它丢饵下去会直接收回来，然后卡在第二杆蓄力阶段，换回我那个正常了。状况跟我尝试换get图标一样。

**Comment by zz2592900** [comment]
> 只修改carrot.png不會影響拋竿，你可能要檢查下語言選項有沒有正確設定

一直是简体中文下更改的.我想更换其他图标，换到上鱼的get.png,也出现这个情况

**Comment by dereklee0310** [comment]
了解，我以為只有吃食物會出問題
請你把`ready.png`修改成這個試試:
![ready](https://github.com/dereklee0310/RussianFishing4Script/assets/76050708/b8e07beb-639b-4e5f-b171-92beb2ee06f8)

**Comment by zz2592900** [comment]
麻了

**Comment by zz2592900** [comment]
底层运动原版图不识别，换成功了；
ready.png的不用换可以使用，换了也会丢第二杆。
carrot.png也不能换你的，也是丢第二杆。已经麻了orz

**Comment by dereklee0310** [comment]
丟第二竿的意思是？

**Comment by zz2592900** [comment]
> 丟第二竿的意思是？

就是丢出去马上就收回来，再抛第二杆蓄力卡住。

**Comment by dereklee0310** [comment]
會出現這種情況代表ready.png識別失敗，請你截取自己畫面上的釣竿就緒字樣嘗試看看。
在我的電腦上測試並沒有辦法復現你的問題。

**Comment by zz2592900** [comment]
> 會出現這種情況代表ready.png識別失敗，請你截取自己畫面上的釣竿就緒字樣嘗試看看。 在我的電腦上測試並沒有辦法復現你的問題。

重新截了下范围大一点已经ok了

**Comment by kingofu2y** [comment]
国服不是可以把语言设置成英文吗，我切过去用的

**Comment by zz2592900** [comment]
> 国服不是可以把语言设置成英文吗，我切过去用的

简中能用不好吗

**Comment by zz2592900** [comment]
大佬还有个问题，如果服务器延迟，鱼的载入时间过久，脚本重启不会把鱼收入护，不知是简中识别的问题还是都这样。

**Comment by zz2592900** [comment]
> 大佬还有个问题，如果服务器延迟，鱼的载入时间过久，脚本重启不会把鱼收入护，不知是简中识别的问题还是都这样。

WARNING: Pirking timeout reached
INFO: Adjusting lure depth
INFO: Pirking
WARNING: Pirking timeout reached
INFO: Adjusting lure depth
INFO: Pirking
WARNING: Pirking timeout reached
INFO: Adjusting lure depth
INFO: Pirking
WARNING: Pirking timeout reached
INFO: Adjusting lure depth
INFO: Pirking

**Comment by dereklee0310** [comment]
> 大佬还有个问题，如果服务器延迟，鱼的载入时间过久，脚本重启不会把鱼收入护，不知是简中识别的问题还是都这样。

提竿收魚逾時後腳本會檢查左下角是否還有上魚的標誌，如果沒有檢測到的話則視為魚脫鉤了->重新拋竿->打狀態。
單純增加收魚逾時檢查的時間也沒辦法完全解決你的問題，請你視自己網路狀況斟酌是否要使用腳本(或是換個梯子)。

**Comment by zz2592900** [comment]
> > 大佬还有个问题，如果服务器延迟，鱼的载入时间过久，脚本重启不会把鱼收入护，不知是简中识别的问题还是都这样。
> 
> 提竿收魚逾時後腳本會檢查左下角是否還有上魚的標誌，如果沒有檢測到的話則視為魚脫鉤了->重新拋竿->打狀態。 單純增加收魚逾時檢查的時間也沒辦法完全解決你的問題，請你視自己網路狀況斟酌是否要使用腳本(或是換個梯子)。

我记得上几个版本会收鱼啊。orz

**Comment by dereklee0310** [comment]
> > > 大佬还有个问题，如果服务器延迟，鱼的载入时间过久，脚本重启不会把鱼收入护，不知是简中识别的问题还是都这样。
> > 
> > 
> > 提竿收魚逾時後腳本會檢查左下角是否還有上魚的標誌，如果沒有檢測到的話則視為魚脫鉤了->重新拋竿->打狀態。 單純增加收魚逾時檢查的時間也沒辦法完全解決你的問題，請你視自己網路狀況斟酌是否要使用腳本(或是換個梯子)。
> 
> 我记得上几个版本会收鱼啊。orz

會收魚只是因為在逾時前入戶的介面剛好成功加載了，轉圈太久還是會出現問題。

**Comment by zz2592900** [comment]
> > > > 大佬还有个问题，如果服务器延迟，鱼的载入时间过久，脚本重启不会把鱼收入护，不知是简中识别的问题还是都这样。
> > > 
> > > 
> > > 提竿收魚逾時後腳本會檢查左下角是否還有上魚的標誌，如果沒有檢測到的話則視為魚脫鉤了->重新拋竿->打狀態。 單純增加收魚逾時檢查的時間也沒辦法完全解決你的問題，請你視自己網路狀況斟酌是否要使用腳本(或是換個梯子)。
> > 
> > 
> > 我记得上几个版本会收鱼啊。orz
> 
> 會收魚只是因為在逾時前入戶的介面剛好成功加載了，轉圈太久還是會出現問題。

orz

**Comment by dereklee0310** [comment]
已修正部分圖片，更新後缺失的圖片請自行截圖。
