### ISSUE TITLE
增加随机延迟

### ISSUE THREAD

**Issue by ZlzF11** [dereklee0310/RussianFishing4Script#21]
脚本的每一项动作的持续时间基本上是固定的，容易被检测为脚本辅助被拉进小鱼塘甚至封禁，建议增加随机延迟或者可以自定义每项动作的持续时间

**Comment by dereklee0310** [comment]
這款遊戲大部分的動作都是在本地運算的，且使用影像辨識本來就有一定的延遲，被檢測到的機率非常低。
因此我沒有打算添加自定義的延遲，請見諒。

**Comment by ZlzF11** [comment]
感谢回复
