### ISSUE TITLE
[BUG]TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

### ISSUE THREAD

**Issue by hpsazz** [dereklee0310/RussianFishing4Script#22]
**Describe the bug**  

**To Reproduce**  
![微信截图_20240423171529](https://github.com/dereklee0310/RussianFishing4Script/assets/167320198/eee0f6da-0d5f-4966-b4cc-fb571a0524a6)

**Expected behavior**  

**Screenshots**  

**Resolution and Window Size**
- Monitor resolution
- Game window size

**Version**  
The version of script, it could be the commit hash or the date of patchnotes in README.

**Settings**  
Paste your config.ini here.
```
[game]
language=en
...
```

**Additional context**

**Comment by dereklee0310** [comment]
看起來是smtp server連線逾時，請檢查你的網路連線和梯子，或是貼上你`.env`中的配置以利定位問題。

**Comment by zz2592900** [comment]
> 看起來是smtp server連線逾時，請檢查你的網路連線和梯子，或是貼上你`.env`中的配置以利定位問題。

必须使用邮件功能才能用脚本了吗？

**Comment by dereklee0310** [comment]
> > 看起來是smtp server連線逾時，請檢查你的網路連線和梯子，或是貼上你`.env`中的配置以利定位問題。
> 
> 必须使用邮件功能才能用脚本了吗？

新版本新增了預設參數的選項，郵件功能預設是開啟的，不想使用的話將`config.ini`中`default_arguments`的參數`e`拿掉即可
```
; default options to use, will be merged into command line arguments at startup
default_arguments = -rcHPRge
; 修改為
default_arguments = -rcHPRg
```

**Comment by dereklee0310** [comment]
> > 看起來是smtp server連線逾時，請檢查你的網路連線和梯子，或是貼上你`.env`中的配置以利定位問題。
> > ![image](https://private-user-images.githubusercontent.com/167320198/324850339-e4409ec4-1ab9-4903-bd3d-6e89c8f1e002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzkxODAsIm5iZiI6MTcxMzg3ODg4MCwicGF0aCI6Ii8xNjczMjAxOTgvMzI0ODUwMzM5LWU0NDA5ZWM0LTFhYjktNDkwMy1iZDNkLTZlODljOGYxZTAwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxMzI4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODc5NDkyYzk4ZTk4OGEzZDRjZjE0Nzc5YWI3NWU5MTcxNWVkYjhlMjlmNTU5YmM3YzEzZDRhZGY0ZWU5ZDExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.451GdUCcfb5R8x9bc_Jqd5nw1B5WK6VBfwHIPo67nyQ)

我沒辦法在我電腦上復現你的問題，你可以:
1. 根據前一則回答關閉此功能
2. 檢查VPN或防火牆設定
3. 嘗試其他SMTP伺服器

**Comment by hpsazz** [comment]
> > > 看起來是smtp server連線逾時，請檢查你的網路連線和梯子，或是貼上你`.env`中的配置以利定位問題。
> > > ![image](https://private-user-images.githubusercontent.com/167320198/324850339-e4409ec4-1ab9-4903-bd3d-6e89c8f1e002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzkxODAsIm5iZiI6MTcxMzg3ODg4MCwicGF0aCI6Ii8xNjczMjAxOTgvMzI0ODUwMzM5LWU0NDA5ZWM0LTFhYjktNDkwMy1iZDNkLTZlODljOGYxZTAwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxMzI4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODc5NDkyYzk4ZTk4OGEzZDRjZjE0Nzc5YWI3NWU5MTcxNWVkYjhlMjlmNTU5YmM3YzEzZDRhZGY0ZWU5ZDExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.451GdUCcfb5R8x9bc_Jqd5nw1B5WK6VBfwHIPo67nyQ)
> 
> 我沒辦法在我電腦上復現你的問題，你可以:
> 
> 1. 根據前一則回答關閉此功能
> 2. 檢查VPN或防火牆設定
> 3. 嘗試其他SMTP伺服器

好的，暂时关闭邮件功能了
