### ISSUE TITLE
消息提醒建议，已测试，只需要替换变量

### ISSUE THREAD

**Issue by hpsazz1** [dereklee0310/RussianFishing4Script#28]
不清楚为什么邮件一直会报SSL安全问题，翻出了之前看到的一个告警类的提醒软件（用自带的软件是免费的）
![image](https://github.com/dereklee0310/RussianFishing4Script/assets/169729938/0d8f77f5-0f50-4ad9-955a-cc5a1fa9d49b)
先上告警平台链接：https://fwalert.com/
告警平台速通：https://fwalert.com/wiki/quick-start/
![image](https://github.com/dereklee0310/RussianFishing4Script/assets/169729938/87ac8b9c-75c7-4813-a0cf-e29f1f1a8e23)
创建转发规则，我这里直接创建RF4
![image](https://github.com/dereklee0310/RussianFishing4Script/assets/169729938/693ed1ad-fcec-4d70-8963-a1d9ea5945e8)
接下来维护模板变量名称，这个随意，为了方便我直接取用项目里的内容
![image](https://github.com/dereklee0310/RussianFishing4Script/assets/169729938/020d8692-cb10-4929-afaf-e1599ea85291)
接下来维护通知简述、通知正文以及通知方式：
![image](https://github.com/dereklee0310/RussianFishing4Script/assets/169729938/47d25e87-f9d3-495a-8f59-1579f0be2c94)
到这里，平台内容维护完毕。
接下来添加用于通知的代码（需要修改，以下内容仅用于测试）：
`import requests

# 指定URL
url = "https://fwalert.com/baadac8e-18be-4373-8005-bb5ce7c8508a"

msg='Cause of termination'
msg1='2024-06-11'
msg2='2024-06-12'
msg3='1'
msg4='99'
msg5='80/19/80%'
msg6='99/1/99%'
msg7='10'
msg8='20'
msg9='21'
msg10='20'
msg11='15'

# 要发送的结构化数据
data = {
    'Cause_of_termination': msg,
    'Start_time': msg1,
    'Finish_time': msg2,
    'Running_time': msg3,
    'Fish_caught': msg4,
    'Marked_Unmarked_Mark_ratio': msg5,
    'Hit_Miss_Bite_ratio': msg6,
    'Alcohol_consumed': msg7,
    'Coffee_consumed': msg8,
    'Tea_consumed': msg9,
    'Carrot_consumed': msg10,
    'Harvest_baits_count': msg11,
    'message': 'RussianFishing4Script: Notice of Program Termination'
}

# 发送GET请求，并将整个字典作为查询参数
response = requests.get(url, params=data)

# 打印响应内容
print(response.text)`

效果如下图所示：
![18751fadb025e80ad33e54e3a0d9317](https://github.com/dereklee0310/RussianFishing4Script/assets/169729938/f991248f-d771-4797-8273-aaaf56a5aecd)
![06b32fc6b2f86f47b57849a7b86b48b](https://github.com/dereklee0310/RussianFishing4Script/assets/169729938/d7fd685e-9870-47af-b1f3-f45fba1f69bf)

后期可以添加类似上星、提醒换铒、钓住地球之类的提醒。

**Comment by hpsazz1** [comment]
阅读不仔细，漏掉了一些内容，变量内容可以不用添加，直接使用相应的键就可以。
![image](https://github.com/dereklee0310/RussianFishing4Script/assets/169729938/f6c89650-fdf2-4955-a6d8-dc9d17e0b65e)
直接

**Comment by hpsazz1** [comment]
Cause of termination:{{Cause_of_termination}}
Start time:{{Start_time}}
Finish time:{{Finish_time}}
Running time:{{Running_time}}
Fish caught:{{Fish_caught}}
Marked / Unmarked / Mark ratio:{{Marked_Unmarked_Mark_ratio}}
Hit / Miss / Bite ratio:{{Hit_Miss_Bite_ratio}}
Alcohol consumed:{{Alcohol_consumed}}
Coffee consumed:{{Coffee_consumed}}
Tea consumed:{{Tea_consumed}}
Carrot consumed:{{Carrot_consumed}}
Harvest baits count:{{Harvest_baits_count}}

**Comment by dereklee0310** [comment]
Implemented.
