### ISSUE TITLE
Marine fishing problem starter kit rod pod 

### ISSUE THREAD

**Issue by nevidiusz** [dereklee0310/RussianFishing4Script#3]
Hey i have a problem with bot, when i catch fish i need to wait ~few minutes to keep fish, they'snt do IT automatic

**Comment by nevidiusz** [comment]
How to sett up to instant keep catched fish?
I use marine rod and reel from starter sea travel pack

**Comment by dereklee0310** [comment]
Is the bot getting stuck before or after the keep/release menu pops up?

**Comment by dereklee0310** [comment]
I think the cause of the problem is that your reel is not fully loaded, please refer to 'Troubleshooting-Stuck at retrieving stage?' in README

**Comment by nevidiusz** [comment]
it could be because of this, do you know how to make it full?

wt., 27 lut 2024, 14:01 użytkownik Derek Lee ***@***.***>
napisał:

**Comment by nevidiusz** [comment]
Btw. Very good job with these bot, I wish you success in the future.

wt., 27 lut 2024, 14:15 użytkownik asd asd ***@***.***> napisał:

**Comment by nevidiusz** [comment]
Problem is solved, thanks alot
