### ISSUE TITLE
作者是否考慮使用cnocr庫製作自動摩擦調節功能

### ISSUE THREAD

**Issue by Errorbus** [dereklee0310/RussianFishing4Script#33]
最近注意到作者沒有更新了，講真的，作者很厲害，腳本功能齊全且實用，作者的無私奉獻實在令我敬佩，同時作為使用者的我一直保持低調使用。我想對您的作品提出一個小小的建議，因為在目前情況下，如果腳本擁有自動摩擦調節功能，所有功能都將得到進化。在宏觀方面，尤其是在挪威海地圖進行掛機，偶爾會碰到一些大魚，這對於挪威海的魚類僅僅依靠最大摩擦進行釣魚是不能滿足的，如果腳本擁有自動調節摩擦功能，那麼這种情況將不復存在了。而對於其他釣魚模式這個功能是可有可無的，因為受限於釣組和裝備差異，我個人認為該功能在挪威海是最為實用的。當然如果其他模式也能擁有該功能的話，那當然是非常完美了。以上是個人的一點建議，我明白對於該功能的製作需要時間和精力，所以無論這個功能是否作者考慮與否，我個人再次對您的無償項目表示感激，期待你的回復。

**Comment by hpsazz1** [comment]
> 最近注意到作者沒有更新了，講真的，作者很厲害，腳本功能齊全且實用，作者的無私奉獻實在令我敬佩，同時作為使用者的我一直保持低調使用。我想對您的作品提出一個小小的建議，因為在目前情況下，如果腳本擁有自動摩擦調節功能，所有功能都將得到進化。在宏觀方面，尤其是在挪威海地圖進行掛機，偶爾會碰到一些大魚，這對於挪威海的魚類僅僅依靠最大摩擦進行釣魚是不能滿足的，如果腳本擁有自動調節摩擦功能，那麼這种情況將不復存在了。而對於其他釣魚模式這個功能是可有可無的，因為受限於釣組和裝備差異，我個人認為該功能在挪威海是最為實用的。當然如果其他模式也能擁有該功能的話，那當然是非常完美了。以上是個人的一點建議，我明白對於該功能的製作需要時間和精力，所以無論這個功能是否作者考慮與否，我個人再次對您的無償項目表示感激，期待你的回復。

作者最近在忙，计划是更新的，你可以进discord关注最新消息

**Comment by Errorbus** [comment]
> > 最近注意到作者沒有更新了，講真的，作者很厲害，腳本功能齊全且實用，作者的無私奉獻實在令我敬佩，同時作為使用者的我一直保持低調使用。我想對您的作品提出一個小小的建議，因為在目前情況下，如果腳本擁有自動摩擦調節功能，所有功能都將得到進化。在宏觀方面，尤其是在挪威海地圖進行掛機，偶爾會碰到一些大魚，這對於挪威海的魚類僅僅依靠最大摩擦進行釣魚是不能滿足的，如果腳本擁有自動調節摩擦功能，那麼這种情況將不復存在了。而對於其他釣魚模式這個功能是可有可無的，因為受限於釣組和裝備差異，我個人認為該功能在挪威海是最為實用的。當然如果其他模式也能擁有該功能的話，那當然是非常完美了。以上是個人的一點建議，我明白對於該功能的製作需要時間和精力，所以無論這個功能是否作者考慮與否，我個人再次對您的無償項目表示感激，期待你的回復。
> 
> 作者最近在忙，计划是更新的，你可以进discord关注最新消息 ![image](https://private-user-images.githubusercontent.com/169729938/347889624-fffcd80a-f7df-4463-a02d-1fd911720454.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MTQ4MDIsIm5iZiI6MTcyMDcxNDUwMiwicGF0aCI6Ii8xNjk3Mjk5MzgvMzQ3ODg5NjI0LWZmZmNkODBhLWY3ZGYtNDQ2My1hMDJkLTFmZDkxMTcyMDQ1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQxNjE1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmJkYWEzYzVmOWMwNDYwOWYzZTFhZmQ3YThiMDEyYjRmYjhhZTMzNjAxYWIwODNiZjFjMzI2MTNlMmQzMjMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p4n5fq2a9VyWU8bLfM7N5yrMEArIbsH2cIcD6I4PTKs)

好的，已了解

**Comment by dereklee0310** [comment]
感謝你對這個project的關注，
點鎖功能已經在做了，但就像前一則回覆中我所回覆的，
我目前的生活重心並不在這上面，所以還請你耐心等候。

你可以加入我們的 [Discord 伺服器](https://discord.gg/BZQWQnAMbY) 以取得最新消息。

**Comment by Errorbus** [comment]
感謝您的回復！我會非常期待您的更新！



---原始邮件---
发件人: "Derek ***@***.***&gt;
发送时间: 2024年7月13日(周六) 上午10:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dereklee0310/RussianFishing4Script] 作者是否考慮使用cnocr庫製作自動摩擦調節功能 (Issue #33)




 
感謝你對這個project的關注，
 點鎖功能已經在做了，但就像前一則回覆中我所回覆的，
 我目前的生活重心並不在這上面，所以還請你耐心等候。
 
你可以加入我們的 Discord 伺服器 以取得最新消息。

**Comment by Errorbus** [comment]
<.>
