### ISSUE TITLE
希望修改判断线杯是否收满的判断

### ISSUE THREAD

**Issue by hhhggbs** [dereklee0310/RussianFishing4Script#35]
截图识别模式会因为背景色不同而影响判断值的波动导致识别不准确，最终使程序卡在Retrieving循环。
我认为可以通过获取游戏界面框内固定点位的rgb值，判断是否收完鱼线。
![ready (3)](https://github.com/user-attachments/assets/63c62f5a-089a-40d5-85bd-a4e55890dcd9)
上图为未收完线
![ready3](https://github.com/user-attachments/assets/9b787fdc-50e9-4452-8a5e-bcceb2dd4f4e)
上图收完线

**Comment by dereklee0310** [comment]
腳本有提供普通和彩虹線杯兩種辨識模式，並且也有靈敏度的選項可以調整，我認為已經足夠應付大部分的使用場景了。
你可以再提出一些需要該功能的理由，我們可以討論看看。
