### ISSUE TITLE
New idea

### ISSUE THREAD

**Issue by nevidiusz** [dereklee0310/RussianFishing4Script#6]
- Add grounbait maker with option keeping or without keeping groundbaits, checking quality of groundbaits, discarding 6> quality 
- Usage keybinds (ec. "6" with alkohol bootle, eating from keybind)

**Comment by nevidiusz** [comment]
Bait selector when bait isn't selected

**Comment by dereklee0310** [comment]
1. The keeping option for groundbait maker will be implemented soon, but I don't think it's necessary to add a quality cheker to it, hope you understand.
2.I believe what you're trying to tell is the functionality of drinking alcohol at scheduled intervals, I'll consider it.
3. I'm not sure what your mean, please give a more detailed description about the behavior of bait selector.

**Comment by nevidiusz** [comment]
It simply happened to me that the bait ran out and it would be nice if instead of the bot having to hold off, it could choose the bait itself.

**Comment by dereklee0310** [comment]
The functionality of replacing broken lure with the same one automatically will be implemented in the future, 
but I don't think most of the players will change the bait for the same spot while AFKing, even when the bait ran out.
The solution will be using `-n` to make the program stop earlier when the number of baits in you inventory is not enough.

**Comment by DcVirus420** [comment]
1. Add auto sell fish in marine fishing 
2. Add auto use ticket for marine fishing 
The best script ever bro i like thes thanks so much

**Comment by dereklee0310** [comment]
> 1. Add auto sell fish in marine fishing
> 2. Add auto use ticket for marine fishing
> 3. Change the broken item for marine fishing
>    The best script ever bro i like thes thanks so much

The first one won't be implemented due to the random spawning location of submarine.
Works on the others are currently in progress, sp please be patient ;)

**Comment by DcVirus420** [comment]
when he catches 100 fish press P and do 360 degree turns until he spots the submarine

**Comment by DcVirus420** [comment]
when he catches 100 fish press P and do 360 degree turns until he spots the submarine

**Comment by Lance880822** [comment]
Added champion or blue crown fish, automatic photo taking function

**Comment by dereklee0310** [comment]
> when he catches 100 fish press P and do 360 degree turns until he spots the submarine i think no good idea but still can try

The submarine might be blocked by the boat model, so it will be a little complicated to implement given the circumstance.
As a workaround, an alert notification for keepnet will be available in the future.

**Comment by dereklee0310** [comment]
> Added champion or blue crown fish, automatic photo taking function

Sometimes the fish model will cover the mark/trohpy/crown icon, which leads to a failed detection.
Perform image preprocessing techniques like masking should solve the problem, but I'm too lazy to do it rn.

For now, you can call `player.save_screenshot()` in `player.handle_fish()` to take screenshot for every fish you caught.

**Comment by dereklee0310** [comment]
Some of the features proposed in this issue have been implemented, and the others will be taken into consideration.  
For new feature requests, use this [issue template](https://github.com/dereklee0310/RussianFishing4Script/issues/new?assignees=&labels=feature&projects=&template=feature_request.md&title=%5BFEATURE%5D) to suggest a new idea.
