### ISSUE TITLE
大佬，海图想快一点切换水层，应该怎么设置哪。

### ISSUE THREAD

**Issue by zz2592900** [dereklee0310/RussianFishing4Script#7]
抽不到鱼的时候，脚本会释放线杯，在继续抽，想问在哪设置时长，缩短抽鱼的时间，默认的有抽鱼的时间有点太长了。

**Comment by dereklee0310** [comment]
修改tackle.py第27行PIRKING_TIMEOUT的值即可設定每次抽魚的時長。

**Comment by zz2592900** [comment]
> 修改tackle.py第27行PIRKING_TIMEOUT的值即可設定每次抽魚的時長。

感谢有你~
