### ISSUE TITLE
關於海釣釣魚，抬桿時間比較久問題

### ISSUE THREAD

**Issue by huoshuigege** [dereklee0310/RussianFishing4Script#9]
作者您好，最近使用了您的腳本，感覺還是很不錯的，但是有點問題，我在海圖使用腳本抽竹刀，線已經完全收緊，但是從收緊後的時間到抬桿的時間中間有5秒鐘，所以想請問一下，有沒有辦法收短中間的時間。

我看了您前面回答的案例，按照之前的改spool_icon_confidence配置的參數也沒有效果
屏幕配置：2560×1440 175hz
遊戲顯示配置：2560×1440  全屏  接口倍數x1
遊戲裝備：大金

望能解答以下問題
1.如何解決抬桿時間比較久的問題（個人建議為：收線的時候就進行抬桿）
2.建議方面：顯示上魚圖標後，能否等待藍條不閃後進行收線，減少脫鉤率
3.疑問：您在說明中有寫email功能，但並未找到配置的方面。

望解答（我掃碼添加了您的WeChat，也希望您能通過一下，可以發送遊戲視頻給您看，協助測試）謝謝作者

**Comment by dereklee0310** [comment]
你可以先試試拿起釣竿後執行`python validate.py`檢查線杯是否能夠被正確的識別。
如果能被正確識別的話，修改`spool_icon_confidence`為更小的值看看問題是否能解決。

關於你提出的問題: 
1. 收線就立刻提桿會加快導環的耗損，所以目前沒有考慮該作法
2. 我不確定藍條與脫鉤率的關聯，可以的話請你描述下它的機制會更好
3. 首次使用`-e`參數會跳出配置的提示，根據該提示修改`.env`中的設定即可 (不使用魔法上網的話可能無法使用該功能)

**Comment by zz2592900** [comment]
> 作者您好，最近使用了您的腳本，感覺還是很不錯的，但是有點問題，我在海圖使用腳本抽竹刀，線已經完全收緊，但是從收緊後的時間到抬桿的時間中間有5秒鐘，所以想請問一下，有沒有辦法收短中間的時間。作者您好，最近使用了您的脚本，感觉还是很不错的，但是有点问题，我在海图使用脚本抽竹刀，线已经完全收紧，但是从收紧后的时间到抬杆的时间中间有5秒钟，所以想请问一下，有没有办法收短中间的时间。
> 
> 我看了您前面回答的案例，按照之前的改spool_icon_confidence配置的參數也沒有效果我看了您前面回答的案例，按照之前的改spool_icon_confidence配置的参数也没有效果 屏幕配置：2560×1440 175hz 遊戲顯示配置：2560×1440 全屏 接口倍數x1 游戏显示配置：2560×1440 全屏 接口倍数x1 遊戲裝備：大金  游戏装备：大金
> 
> 望能解答以下問題 望能解答以下问题 1.如何解決抬桿時間比較久的問題（個人建議為：收線的時候就進行抬桿） 1.如何解决抬杆时间比较久的问题（个人建议为：收线的时候就进行抬杆） 2.建議方面：顯示上魚圖標後，能否等待藍條不閃後進行收線，減少脫鉤率 2.建议方面：显示上鱼图标后，能否等待蓝条不闪后进行收线，减少脱钩率 3.疑問：您在說明中有寫email功能，但並未找到配置的方面。 3.疑问：您在说明中有写email功能，但并未找到配置的方面。
> 
> 望解答（我掃碼添加了您的WeChat，也希望您能通過一下，可以發送遊戲視頻給您看，協助測試）謝謝作者望解答（我扫码添加了您的WeChat，也希望您能通过一下，可以发送游戏视频给您看，协助测试）谢谢作者

你上大点的鱼收线的时候就抬杆很容易卡船底，有5秒的时间是因为它检测不到你线杯状态。 你转转视角，调调画面对比度曝光度。

**Comment by zz2592900** [comment]
> 作者您好，最近使用了您的腳本，感覺還是很不錯的，但是有點問題，我在海圖使用腳本抽竹刀，線已經完全收緊，但是從收緊後的時間到抬桿的時間中間有5秒鐘，所以想請問一下，有沒有辦法收短中間的時間。
> 
> 我看了您前面回答的案例，按照之前的改spool_icon_confidence配置的參數也沒有效果 屏幕配置：2560×1440 175hz 遊戲顯示配置：2560×1440 全屏 接口倍數x1 遊戲裝備：大金
> 
> 望能解答以下問題 1.如何解決抬桿時間比較久的問題（個人建議為：收線的時候就進行抬桿） 2.建議方面：顯示上魚圖標後，能否等待藍條不閃後進行收線，減少脫鉤率 3.疑問：您在說明中有寫email功能，但並未找到配置的方面。
> 
> 望解答（我掃碼添加了您的WeChat，也希望您能通過一下，可以發送遊戲視頻給您看，協助測試）謝謝作者

你上大点的鱼收线的时候就抬杆很容易卡船底，有5秒的时间是因为它检测不到你线杯状态。 你转转视角，调调画面对比度曝光度。
